services:
  - type: web
    name: validar-boletimcromaagosto
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    plan: free
    region: oregon
    envVars:
      - key: SECRET_KEY
        value: "your_secret_key_here"
      - key: FLASK_ENV
        value: "production"
      - key: DEBUG
        value: "false"
    healthCheckPath: /
    autoDeploy: true